--- #YAML:1.0
name:               Business-Tax-VAT-Validation
version:            1.02
abstract:           A class for european VAT numbers validation.
author:
    - Bernard Nauwelaerts <bpgn@cpan.org>
license:            GPL_3
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    HTTP::Request::Common:  1
    LWP::UserAgent:       1
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
